# Site settings
title: ANTH&206
email: tbatey@my.lowercolumbia.edu
description: > # this means to ignore newlines until "baseurl:"
  A exploratory website and blog for ANTH&206 (Cultural Anthropology) at Lower Columbia College
baseurl: "/Anth206" # the subpath of your site, e.g. /blog/
url: "http://tbatey.org" # the base hostname & protocol for your site
twitter_username: DocBatey
github_username:  bateyt
permalink: /:year/:month/:title.html

# Build settings
markdown: kramdown
